### ISSUE TITLE
Long-running commands (several minutes+) cause stream of exceptions when finished

### ISSUE THREAD

**Issue by kierenj** [sedders123/phial#176]
Long-running commands complete fine, but then exceptions are thrown in a loop

Not sure of the limit, but 1 minute works fine without errors

**Comment by sedders123** [comment]
Having tried a 30 minute long command (code below) I am unable to reproduce this issue. Can you provide any further reproduction steps?

```python
@bot.command("long-command")
def long_command():
    time.sleep(60 * 30)
    return "Done"
```
