### ISSUE TITLE
Failing CircleCI tests

### ISSUE THREAD

**Issue by dylmye** [sedders123/phial#87]
**Describe the bug**
The static type check is failing - it seems that the prefix config is being set to an object somewhere.

**To Reproduce**
n/a

**Expected behavior**
Test passes

**Actual Behaviour**
The following error is thrown:
```
#!/bin/bash -eo pipefail
. venv/bin/activate
mypy phial --strict-optional --disallow-untyped-defs --disallow-incomplete-defs --disallow-untyped-decorators --no-implicit-optional --disallow-subclassing-any

phial/commands.py:12: error: Unsupported left operand type for + ("object")
phial/commands.py:20: error: Unsupported left operand type for + ("object")
phial/commands.py:21: error: Incompatible return value type (got "object", expected "str")
phial/bot.py:150: error: Argument 1 to "startswith" of "str" has incompatible type "object"; expected "Union[str, Tuple[str, ...]]"
Exited with code 1
```

**Versions (please complete the following information):**
n/a

**Additional context**
The default config for `prefix` is `!` (see [here](https://github.com/sedders123/phial/blob/develop/phial/bot.py#L22)), a string. In all of the tests on `prefix`, `/` is used (see [here](https://github.com/sedders123/phial/blob/develop/tests/test_bot.py#L45))

**Comment by sedders123** [comment]
Thanks for the report! Fixed in #86
